title: Zero[Z.W.T] Blog
email: zerozwt1991@gmail.com
description: ZeroZWT的个人博客，啥都写写。
lang: zh_CN
twitter_username: zerozwt
github_username:  zerozwt

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

header_pages:
  - about.md

paginate: 10

lang: 'zh-CN'

plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - gen_pages.py